Feature/12 support nested matchers
exasol/hamcrest-resultset-matcher pull request #13
Opened 2020-09-25 13:21 UTC by redcatbear

Closes #12.

2020-09-25 16:10 UTC, jakobbraun requested changes

2020-09-25 16:10 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> + * @param <T> Matcher type
Why do you need this type. Isn't it always `ResultSet`?

2020-09-28 05:03 UTC, redcatbear commented on doc/changes/changes_1.0.0.md
> +# hamcrest-resulset-matcher 1.0.0, released 2020-10-25
Oopps. I am ahead of my time, it seems.

2020-09-28 05:08 UTC, redcatbear commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> + * @param <T> Matcher type
You have a point. I should only support `ResultSet` and derived interfaces.

2020-09-28 05:08 UTC, redcatbear commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> +            } else if (this.fuzzy) {
No. For the whole table. Not per cell.

2020-09-28 06:42 UTC, jakobbraun requested changes

2020-09-28 06:42 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> +            for (final List<Matcher<?>> expectedRow : this.cellMatcherTable) {
```suggestion
            for (final List<Matcher<?>> cellMatcherRow : this.cellMatcherTable) {
```

2020-09-28 06:42 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> +            for (final Matcher<?> expectedValue : expectedRow) {
```suggestion
            for (final Matcher<?> cellMatcher : expectedRow) {
```

2020-09-28 06:42 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
> +            final List<Matcher<?>> expectedRow) {
```suggestion
            final List<Matcher<?>> cellMatcherRow) {
```

2020-09-28 07:00 UTC, jakobbraun approved these changes

2020-09-28 07:02 UTC, merged