feature/21-fuzzy-matching-with-tollerance
exasol/hamcrest-resultset-matcher pull request #23
Opened 2020-12-04 18:29 UTC by jakobbraun

Closes #21

2020-12-07 08:18 UTC, redcatbear requested changes

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +     * Create a {@link UpcastOnlyCellMatcher}.
```suggestion
     * Create a new instance of an {@link UpcastOnlyCellMatcher}.
```

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +     * @param <T>      type of the matcher
```suggestion
     * @param <T>      type of the matched value
```

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +    private String explanation;
```suggestion
    private String explanation = "";
```

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +        this.explanation = "";
```suggestion
```

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +        this.explanation = "";
There should not be a side effect on the explanation in the matcher.

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +            return true;
This is counter-intuitive. In case where you are not handling numbers, an exact match would be the right thing to do.

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +        description.appendText("type safely castable to ").appendText(this.expected.getClass().getName());
```suggestion
        description.appendText("type can safely be cast to ").appendText(this.expected.getClass().getName());
```

2020-12-07 08:18 UTC, redcatbear commented on src/test/java/com/exasol/matcher/AbstractCellValueMatcherTest.java
> +    void testFuzzyMismatchDecimalWithFractionToLong() {
:+1:

2020-12-07 08:18 UTC, redcatbear commented on src/test/java/com/exasol/matcher/AbstractCellValueMatcherTest.java
> +                FuzzyCellMatcher.fuzzilyEqualTo(26.82, BigDecimal.valueOf(0.015)));
```suggestion
                FuzzyCellMatcher.fuzzilyEqualTo(26.82, BigDecimal.valueOf(0.015)));
```

When looking at this, I think we should have convenience methods that accept non-big-int tolerances.

2020-12-07 08:18 UTC, redcatbear commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +        this.explanation = "\nThe actual type is bigger than the expected. You can disable this check by using the NO_TYPE_CHECK fuzzy-mode.";
```suggestion
        this.explanation = "\nThe actual type is bigger than the expected. You can disable this check by using the NO_TYPE_CHECK fuzzy-mode.";
```

While I like mitigations in error messages, this is an assertion message and should only contain the relevant results.

2020-12-08 07:17 UTC, jakobbraun commented on doc/user_guide/user_guide.md
> +The `ResultSet` matcher is the implementation of a [Java Hamcrest matcher](JavaHamcrest). The Hamcrest (an anagram of "
why not it's easier to read for everyone and in the markdown viewers (like GitHub) it's the same.
The long lines only make it hard to read.

2020-12-08 07:20 UTC, jakobbraun commented on doc/user_guide/user_guide.md
> +The `ResultSet` matcher is the implementation of a [Java Hamcrest matcher](JavaHamcrest). The Hamcrest (an anagram of "
Oh. I just realised some formater broke the lines in the sentence... That's of course not nice

2020-12-08 07:22 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +The `ResultSet` matcher is the implementation of a [Java Hamcrest matcher](JavaHamcrest). The Hamcrest (an anagram of "
1. All Markdown readers I came across support soft-wrapping.
1. If you add new text, multiple lines shift, leading to a broader than necessary diff.
1. It's easier to see real paragraph changes when line breaks are reserved for them.

2020-12-08 07:22 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/CellMatcherFactory.java
> +
what changed?

2020-12-08 07:32 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/TypeMatchMode.java
> + * Modes for fuzzy matching.
```suggestion
* Modes for result set matching.
```

2020-12-08 07:34 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/UpcastOnlyCellMatcher.java
> +        description.appendText("type safely castable to ").appendText(this.expected.getClass().getName());
```suggestion
        description.appendText("type that can safely be cast to ").appendText(this.expected.getClass().getName());
```

2020-12-10 14:14 UTC, jakobbraun commented on src/main/java/com/exasol/matcher/ResultSetStructureMatcher.java
>              description.appendText(" (fuzzy match)");
I removed it copletely since the tests now print it anyway.

2020-12-11 06:58 UTC, jakobbraun commented on src/test/java/com/exasol/matcher/AbstractCellValueMatcherTest.java
> +                FuzzyCellMatcher.fuzzilyEqualTo(26.82, BigDecimal.valueOf(0.015)));
I'm not sure if it's a good idea to define tolerance as floating-point numbers. I think tolerance should be very exact.

2020-12-11 06:58 UTC, jakobbraun commented on src/test/java/com/exasol/matcher/AbstractCellValueMatcherTest.java
> +                FuzzyCellMatcher.fuzzilyEqualTo(26.82, BigDecimal.valueOf(0.015)));
On the other hand's side this constructor of BigDecimal also uses a double as input...

2020-12-17 11:52 UTC, redcatbear requested changes

2020-12-17 11:52 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +                        .matches());
Why the extra indentation?
It's still the same level.

2020-12-17 11:52 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +Of course you can nest matcher in the nested matcher. That's the beauty of hamcrest.
```suggestion
Of course you can nest matchers in the nested matcher. That's the beauty of Hamcrest.
```

2020-12-17 11:52 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +When comparing floating-point numbers you sometimes want only to compare with a given precision. So you don't want to check that all decimal digits are exactly equal but match with a certain toleranc
```suggestion
When comparing floating-point numbers you might want to compare the actual value against the expectation within a given tolerance. That way actual and expected don't need to be an exact match &mdash; it just needs to be close enough.
```

2020-12-17 11:52 UTC, redcatbear commented on doc/user_guide/user_guide.md
>  ```
```suggestion
final BigDecimal tolerance = BigDecimal.valueOf(0.001);
assertThat(result,
        table()
        .row(CellMatcherFactory.cellMatcher(1.234, TypeMatchMode.STRICT, tolerance))
        .matches();
```

2020-12-17 11:52 UTC, redcatbear commented on src/main/java/com/exasol/matcher/CellMatcherFactory.java
> +
Remove empty line please.

2020-12-17 11:52 UTC, redcatbear commented on src/main/java/com/exasol/matcher/EnhancedAllOfMatcher.java
> +     * @param matchers matcher to combine
```suggestion
     * @param matchers matchers to combine
```

2020-12-17 11:52 UTC, redcatbear commented on src/test/java/com/exasol/matcher/AbstractCellValueMatcherTest.java
> +                FuzzyCellMatcher.fuzzilyEqualTo(26.82, BigDecimal.valueOf(0.015)));
I accept the precision argument. Continue.

2020-12-18 06:19 UTC, redcatbear approved these changes

2020-12-18 08:47 UTC, merged